services:
  postgres:
    image: postgres:18-alpine
    container_name: ecom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecom_dev
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: ecom_password
    ports:
      - "5433:5432"   # 5433 bên ngoài → 5432 trong container, để tránh xung đột với postgres của máy host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: